### ISSUE TITLE
panic index out of bounds in pyspy

### ISSUE THREAD

**Issue by korniltsev** [grafana/pyroscope-rs#170]
```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.3.14/src/python_interpreters.rs:296:20:
index out of bounds: the len is 20 but the index is 20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.3.14/src/sampler.rs:218:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

**Comment by draincoder** [comment]
Hello! Is it possible to somehow catch panics and restart the profiling process in runtime?

**Comment by korniltsev** [comment]
I don't think so. We need to fix panics

**Comment by ethervoid** [comment]
Do you know what is causing it? We're experiencing it too

**Comment by korniltsev** [comment]
I suspect it is the nonblocking way of operating of pyspy. One of the ways to reproduce this is to import+del some module in a loop.

**Comment by knowald** [comment]
Same error here with `pyspy` version `0.4.0`. Celery workers with the same entrypoint are properly tracked, while our FastAPI uvicorn logs this on start with the thread crashing out of bounds. Good that it's nonblocking, but first question would be how to properly handle this background panic? It looks like the problem might be related to Python 3.12, and a relevant PR is open here: https://github.com/benfred/py-spy/pull/736

```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.4.0/src/python_interpreters.rs:251:20:
index out of bounds: the len is 21 but the index is 21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.4.0/src/sampler.rs:264:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

**Comment by korniltsev** [comment]
I will close this as a dup of https://github.com/grafana/pyroscope-rs/issues/197
